### ISSUE TITLE
Incorrect scale on iOS with constrained unzoomed width

### ISSUE THREAD

**Issue by 0x6e6562** [rpearce/react-medium-image-zoom#146]
This issue is a:

- Bug report

## Expected behavior

That the zoomed image would scale correctly on all platforms.

## Actual behavior

On iOS, the zoomed image is scaled based on the rendered size of the unzoomed image and appears blurry.

The zooming does work as expected on desktop and Android. This issue appears to be related to iOS only.

## Steps to reproduce behavior

1. Apply a constrained width to an unzoomed image (e.g. 20%)
2. View the page with an iOS device
3. Run the linked the example below in the dev server and view it with an iOS device (both Safari and Chrome for iOS exhibit the same behavior).

## Link to repository/example of behavior

I have patched the example to apply a 20% width style attribute that highlights the behavior - [the patch to the upstream is here
](https://github.com/rpearce/react-medium-image-zoom/compare/master...switchsmith:ios-blur)

This runs with the pre-configured node dev server.

## Notes

This example contains the fix from #101, so hopefully this issue is not a duplicate of that.

I had a go at trying to tweak the transform logic here:

https://github.com/rpearce/react-medium-image-zoom/blob/25d563e3e0d03eb7cc72e560e7e1e035feff2a1d/src/Zoom.js#L141

I made some improvements by adding a `{zoom: 2}` property and halving the `scale` factor. This appears to make the device render the full resolution. So the image is now clear. But the side effect is that the `X,Y` coordinate logic pushes the image out of the viewport.

I saw that a rewrite of the library is in progress, so I decided to first report this issue and provide a means of reproducing the symptom first.

**Comment by rpearce** [comment]
@0x6e6562 You are amazing for being so detailed here. If this is a bug that you need fixed and isn't too far-reaching, you and I can see about getting a patch out there.

The rewrite, at present, is
  * a ways off
  * will change the API drastically
  * will work completely different internally
  * will ultimately be really good

... so I wouldn't hold my breath on that one.

How would you like to proceed?

**Comment by 0x6e6562** [comment]
Thanks for the heads up about the rewrite - in this case, just being able to patch this one particular issue on the current master branch would be the best way forward.

I did try to fix the issue myself but it felt like choosing the appropriate way to patch the transform was going to be tricky to get right, so I was kind of wondering whether you would have a better idea of the best way to proceed (i.e. not to introduce a regression for other platforms).

Also, I wasn't quite sure what the correct logic is for the `x,y` coordinates - maybe you had more experience with this?

**Comment by rpearce** [comment]
@0x6e6562 looking at this now to see what we can do... I'll get back to you shortly

**Comment by rpearce** [comment]
@0x6e6562 Good news: scaling the original image in dev tools does actually work, so there is hope. Bad news, I haven't figured this out yet. I'll get there!

**Comment by rpearce** [comment]
@0x6e6562 I've been slammed the past few days and haven't been able to come back to this yet. I will take a look over the next few days

**Comment by rpearce** [comment]
@0x6e6562 I've narrowed the issue down to being because of using `width` & `height` in addition to `scale()` on the added image (the one that is thrown onto the overlay, scaled up and eventually replaced by a bigger one), and I have yet to figure out a solution that doesn't rip out how the zooming works in the first place. It currently relies on the `transform` and `transition` on the `transform` to provide the animation, but if I change that, I change how all the things work.

I'm going to make one efforting using `vh` and `vw` instead of `scale()` to see if I can achieve the same result, but if not, I'm going to have to leave this for now and factor all this into the rewrite.

**Comment by 0x6e6562** [comment]
@rpearce Many thanks for keeping me in the loop - I fully appreciate the intricacy, having tried to fix the issue myself...

**Comment by pavelkornev** [comment]
facing the same problem on iOS... is it still planned to be fixed in near future?

**Comment by rpearce** [comment]
@pavelkornev This is taking longer than expected, so I can't give much of an estimate at the moment. What @spencerfdavis and I are looking at doing is completely changing how the zooming works so that this issue (and others) should allegedly just not happen. This isn't sponsored by our day job, so finding the time is interesting.

Happy to look at PRs if there's a fix you figure out in the mean time

**Comment by rpearce** [comment]
FYI now that `v4` is in `alpha`, I've put this at the top of [the project board](https://github.com/rpearce/react-medium-image-zoom/projects/1) to make it the next thing I look in to to see if I've been able to resolve it or not.

**Comment by 0x6e6562** [comment]
I'll follow the progress on this issue and will test it out on my own site when you think it's ready to try out.

**Comment by rpearce** [comment]
Sounds good. Still a few quirks, but I think this isn't going to be an issue

**Comment by rpearce** [comment]
...and I was wrong. It's still an issue. This is 💯 priority.

**Comment by rpearce** [comment]
Update:
1. it looks like this is only an issue when using `background-image`s on something like a `div`. Still trying to get to the bottom of it, but it doesn't seem like it's a problem on iOS for the other use cases
1. separately, it looks like there's a little bit of a positioning bug on mobile phone sizes

**Comment by rpearce** [comment]
Update:
* I think I've fixed `<img />` tags being blurry on Safari with https://github.com/rpearce/react-medium-image-zoom/pull/193 and is published at `react-medium-image-zoom@4.0.0-alpha.4`.
* The blurriness bug is still present on `<div>`s with `background-image`, so this bug is not resolved
* There's still that mobile positioning bug

**Comment by rpearce** [comment]
This _should_ be 99% fixed in #194. The only outstanding thing I see with regard to blurriness will be handle in https://github.com/rpearce/react-medium-image-zoom/issues/195.

Please let me know if you have continued issues!

**Comment by 0x6e6562** [comment]
Many thanks @rpearce  for reworking the library and also for keeping this issue up to date 👍 

I've just upgraded to `4.0.0-alpha.8` to test this out, but I'm getting the following hook issue when using the controlled or uncontrolled components:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

Using a hook in a hello world component seems to work fine, it is just when I import `Zoom` or `ControlledZoom` from `react-medium-image-zoom` that I get this error message.

I'll try to reduce the problem to identify the root cause.

**Comment by rpearce** [comment]
@0x6e6562 I've just today noticed this on another library of mine, as well. My first guess is that it's something related to my usage of rollup.js, but TBD. Thanks for the heads up.

**Comment by 0x6e6562** [comment]
I noticed this with a Gatsby app and my first thought was that Gatsby was somehow loading multiple versions of react. I tried to depend on `git://github.com/rpearce/react-medium-image-zoom#8d3db6c` rather than `^4.0.0-alpha.8` but initially this doesn't load because of an webpack-esque error:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Unexpected token (64:4)

File: node_modules/react-medium-image-zoom/source/Controlled.js:64:4
```

So I might need to find out how webpack/babel this properly.

**Comment by rpearce** [comment]
Thanks for your patience with working through this with me! We'll get there.

**Comment by rpearce** [comment]
Let's movee this conversation over to https://github.com/rpearce/react-medium-image-zoom/issues/199

**Comment by rpearce** [comment]
Should be resolved... I just tested this out in a brand new `create-react-app`:
```
$ npx create-react-app my-app
$ cd my-app
$ npm i react-medium-image-zoom@alpha
```
then
```js
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

// ...

<Zoom>
  <img src={logo} className="App-logo" alt="logo" />
</Zoom>
```

and it looks to be working...

**Comment by 0x6e6562** [comment]
Many thanks @rpearce for all of your hard work on this issue 👍 

I've followed the hello world `create-react-app` with `^4.0.0-alpha.9` and when you nest the React logo inside the `Zoom` component, it is fine.

However, testing with a real image I still see the blurriness on iOS/Safari:

```js
import React from 'react';
import './App.css';

import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <Zoom>
          <img width='80px' height='160px' src='https://source.unsplash.com/KK8PSWsYknQ/800x1600'/>
        </Zoom>
      </header>
    </div>
  );
}

export default App;
```

You don't get the same blurriness on OSX/Safari or any version of Chrome (OSX or Android).

The blurriness seems to be proportional the unzoomed viewport. The larger the unzoomed viewport, the less blurry the zoomed image is. However, increasing the size of the unzoomed viewport contradicts the purpose of a zoom component.

It's really weird that this is only reproducible on an iOS device.

**Comment by 0x6e6562** [comment]
I've just checked the behavior on an iOS simulator and it is similar to a real iOS device. Here is a side by side of zooming on Safari/simulator vs Safari/OSX:

<img width="898" alt="Screenshot 2020-01-05 00 33 31" src="https://user-images.githubusercontent.com/14088/71773313-2fdc9e00-2f53-11ea-8b6b-06bc25d3c2bb.png">

**Comment by 0x6e6562** [comment]
I think I may have found the cause of the problem - Safari/OSX handles `transform: translateZ(0)` differently to Safari/iOS.

The style

```css
/* To fix Safari img blurriness */
.content img {
  transform: translateZ(0);
}
```

Produces a smoother result on Safari/OSX, but results in a blurred image on Safari/iOS.

Removing this selector fixes the blurriness on iOS, at the cost of a less smooth transition on OSX.

I guess you could do a user-agent-specific selector to get the best of both worlds?

**Comment by rpearce** [comment]
Wow, that's something. I'll take your advice (wish I didn't need to), but I'll first see if I can find another workaround on Safari (macOS).

* * *

You are amazing for working through this with me. I've added you to https://github.com/rpearce/react-medium-image-zoom#contributors.

**Comment by 0x6e6562** [comment]
No need to thank me, very happy to help out 👍 

 I take your point about the the agent-specific selector - it's clunky and feels like it might to come back to bite in the future. I only suggested it because off hand, I couldn't think of a way to handle Safari on different platforms.

And I guess for completeness we'd also need to check the behavior on iPad - given the delta between OSX and iOS, iPhone and iPad might diverge as well.

**Comment by rpearce** [comment]
I had tested this on a relatively new iPad Pro, and it looked :+1: to me using my examples, but it's not impossible that was just wishful thinking

**Comment by rpearce** [comment]
@0x6e6562 I'm not sure how I feel at the moment how big of a deal the transition issue is on Safari in general, so I'm going to mark it as "good enough". I removed the `transform` b/c Safari on macOS looked good enough, as did iOS 8 on the iOS simulator.

Please let me know if this is insufficient or you find something else!

**Comment by 0x6e6562** [comment]
Using a manually imported rollup build of the CSS I had come to the same conclusion myself - the benefit of removing the `transform` attribute on iOS significantly outweighs the almost unnoticeable jumpy-ness on OSX. Also, it something that you will probably only notice when you are actually developing the app, as opposed to a regular site user. Furthermore, doing anything user agent specific is likely to give you enough rope to hang yourself, so I think the approach you've settled on is the best 👍

**Comment by rpearce** [comment]
Thanks. If I get annoyed enough by it or someone brings it up, we'll open a separate issue.
